version: '3.8'

services:
  backend:
    container_name: dotnetauth-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8102:5000"
    networks:
      - soben-network

networks:
  soben-network:
    external: true